# Generated by Django 3.2.9 on 2021-12-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
